### ISSUE TITLE
Additional Screenshots

### ISSUE THREAD

**Issue by adamgreig** [nsonnad/base16-ipython-notebook#3]
Hi! Thanks for making these fantastic themes.

I whipped up a short script to generate a screenshot of all of them:

```fish
echo "Activate firefox window (3 seconds...)"
sleep 3
for theme in base16-*
    cat custom_preamble.css $theme > custom.css
    echo -n "Displaying $theme, screenshot in 5..."
    xdotool key F5
    sleep 1
    echo -n " 4..."
    sleep 1
    echo -n " 3..."
    sleep 1
    echo -n " 2..."
    sleep 1
    echo -n " 1..."
    sleep 1
    import -w 26211608 "/home/adam/Pictures/ipynb-themes/$theme.png"
    echo " done. Next theme..."
end
```

The results are here: http://imgur.com/a/G1jhr

Feel free to link or download and use them! If you like I could add a PR with all the screenshot images and an index page but perhaps just linking to the album is easier.

**Comment by nsonnad** [comment]
Thanks, perhaps we could include your script and sample notebook as a way for people to test their custom styles?

**Comment by adamgreig** [comment]
Sure, though it's probably not the most portable script -- only works on Linux at least and you have to look up the window number for firefox (something like `xdotool search --name "Mozilla Firefox"`).

I could dump the notebook somewhere but perhaps if people are going to test their custom styles they can whip up their own with whatever content they want to see tested?
