### ISSUE TITLE
Any way keep the themes when exporting pages as HTML?

### ISSUE THREAD

**Issue by kebarcla** [nsonnad/base16-ipython-notebook#5]
Hello,

These themes look great: thanks for making them.

If I'm using IPython NB to author content for the web, is there a way I can keep the theme when I export the file as HTML to host on my web server?

Thanks
Ken

**Comment by nsonnad** [comment]
Hi Ken, this is worth looking into. Any chance you could provide a sample HTML page that you've exported from iPyNB?
