### ISSUE TITLE
Unchanged background on Jupyter

### ISSUE THREAD

**Issue by alkalait** [nsonnad/base16-ipython-notebook#7]
The background color stays white on all themes. Any idea how to force the color change?

**Comment by tslevi** [comment]
I have the same issue.

**Comment by Zebreu** [comment]
div#notebook {background-color: #2b303b;}
div#notebook-container {background-color: #2b303b;}
div#ipython-main-app {background-color: #2b303b;}

You can add these lines in the Globals section (with whatever color that's in the body's background-color variable) and it fixes it.
